[general]
protocol = "redisresp"
interval = 5 # seconds
windows = 5 # run for 5 intervals
clients = 1 # use a single client thread
poolsize = 1 # each client has 1 connection per endpoint
tcp_nodelay = false # do not enable tcp_nodelay
request_timeout = 200 # milliseconds
connect_timeout = 200 # milliseconds
request_ratelimit = 100_000 # 100K requests/second
connect_ratelimit = 1000 # 1K connects/second
warmup_hitrate = 0.9 # do warmup until 90% hitrate is achieved
waterfall = "waterfall.png" # produce a waterfall at end of run
endpoints = [ # specify the endpoints in the config
    "127.0.0.1:6379",
]

[[keyspace]]
length = 8 # 8 byte keys
count = 10_000 # limit to 10K keys
weight = 9 # this keyspace will be used for 90% of requests
commands = [ # get:set ratio is 4:1 - read heavy
    {weight = 4, action = {type = "get"}},
    {weight = 1, action = {type = "set"}},
    {weight = 1, action = {type = "mget", key_count = 2}},
    {weight = 1, action = {type = "mset", key_count = 2}},
]
values = [ # uses multiple value lengths with different weights
    {length = 64, weight = 8}, # 80% as 64 byte values
    {length = 128, weight = 1}, # 10% as 128 byte values
    {length = 256, weight = 1}, # 10% as 256 byte values
]
